### PR TITLE
3d visualization with vtkplotter

### PR DESCRIPTION
**Pull request by ahinoamp**
1. Added some functions to output.py to visualized noddy files in 3d.
2. Added two example files: a notebook and python example
3. Added an additional history file to the examples folder

(accidentally committed my gitignore..)

### CODE REVIEW

**Comment by flohorovicic** [comment]
Thanks a lot, Noe! Fantastic contribution to pynoddy🥇, will definitely be very helpful to many users (including me, to be sure).

**Comment by ahinoamp** [comment]
Thanks Florian. Next week Tuesday or Wednesday I'll add the next installment: a function FaultTraceCSV2PyNoddyHistory(csvfilelocation, stratigraphydictionary, historyfilename) that takes a csv with faults and turns it into a pynoddy model.

**Comment by markjessell** [comment]
Hi Ahinoam,

That sounds cool, maybe we can merge FaultTraceCSV2PyNoddyHistory with the map2loop (https://github.com/Loop3D/map2loop) code at some stage to feed noddy and the other 3D packages in a common way?

Cheers

Mark Jessell
UWA

**Comment by ahinoamp** [comment]
Hi Mark,

Wow! I just looked at your Loop3D code. Looks very impressive.
I will write you an email in a moment and we can set up a time to talk about code combination and collaboration.

Noe

**Comment by markjessell** [comment]
Impressive but very flakey! Yes let’s talk.

Cheers
Mark

Mark Jessell
Professor/ Western Australian Fellow
Centre for Exploration Targeting/ SES • M006, Perth WA 6009 Australia
T +61 8 6488 5803 • E mark.jessell@uwa.edu.au

________________________________

**Comment by flohorovicic** [comment]
Hi Noe and Mark,

Fantastic, perfect chance to get Noddy into loop and to get all modeling efforts closer together! 

Cheers,

    — Florian —

**Pull request merged**
